{% set version = "0.1.0" %}

package:
  name: usgscam
  version: {{ version }}

source:
    git_url: https://github.com/USGS-Astrogeology/CSM-CameraModel
    git_rev: master
build:
  number: 3

detect_binary_files_with_prefix: true

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.10
    - cython >=0.27
    - libcsm
    - cycsm
    - vc 14  # [win and py>=35]
  run:
    - python
    - numpy >=1.10
    - libcsm
    - cycsm
    - vc 14  # [win and py>=35]

test:
  requires:
    - pytest

  imports:
    - usgscam

about:
  home: https://github.com/USGS-Astrogeology/CSM-CameraModel
  license: Unlicense
