
{% set name = "usgscsm" %}
{% set version = "main" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: 'https://github.com/DOI-USGS/usgscsm.git'
  git_tag: {{ version }}

build:
  number: 0
  skip: true  # [win]


requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.10
    - make
    - nlohmann_json
    - eigen
  host:
    - csm
    - vc  # [win]
  run:
    - csm

test:
  commands:
    - test -e $PREFIX/lib/csmplugins/libusgscsm${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: https://github.com/DOI-USGS/usgscsm
  license: None
summary: "USGS Astrogeology Community Sensor Model compliant sensor models."
