
package:
  name: usgscsm
  version: 1.7.0

source:
  git_url: https://github.com/acpaquette/usgscsm.git
  git_branch: proj_stuff
build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - vc 14  # [win]
    - cmake >=3.10
    - libcsm
    - vc 14  # [win]
  run:
    - vc  # [win]

test:
  commands:
    - test -e $PREFIX/lib/libusgscsm.so  # [linux]
    - test -e $PREFIX/lib/libusgscsm.dylib  # [osx]
    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: https://github.com/DOI-USGS/usgscsm
  license: None
summary: "USGS Astrogeology Community Sensor Model compliant sensor models."
