
package:
  name: usgscsm
  version: "1.0.0"

source:
  url: https://github.com/USGS-Astrogeology/CSM-CameraModel/archive/1.0.0.zip
  sha256: dd0894d0a6c370db0a0376bd4c7ea510f0b172a53b8216bba699c51a28f49c76
build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - vc 14  # [win]
    - cmake >=3.10
    - libcsm
    - vc 14  # [win]
  run:
    - vc  # [win]

test:
  commands:
    - test -e $PREFIX/lib/libusgscsm.so  # [linux]
    - test -e $PREFIX/lib/libusgscsm.dylib  # [osx]
    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: https://github.com/USGS-Astrogeology/CSM-CameraModels
  license: None
summary: "USGS Astrogeology Community Sensor Model compliant sensor models."
