
{% set name = "usgscsm" %}
{% set version = "proj_stuff" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: .
    url: https://github.com/acpaquette/{{ name }}/archive/{{ version }}.tar.gz
    sha256: e6aa7830d216b878094b470971e1695fa34b7893e346c2449b7a8ae162db70f5

build:
  number: 0
  skip: true  # [win]


requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.10
    - make
  host:
    - csm
    - nlohmann_json
    - eigen
    - vc  # [win]
  run:
    - {{ pin_compatible('nlohmann_json', min_pin='x.x', max_pin='x.x') }}
    - csm
    - eigen

test:
  commands:
    - test -e $PREFIX/lib/csmplugins/libusgscsm${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: https://github.com/DOI-USGS/usgscsm
  license: None
summary: "USGS Astrogeology Community Sensor Model compliant sensor models."
