
package:
  name: usgscsm
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: https://github.com/DOI-USGS/usgscsm.git
build:
  string: {{ environ.get("GIT_DESCRIBE_HASH", "") }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - vc 14  # [win]
    - cmake >=3.10
    - libcsm
    - sqlite
    - vc 14  # [win]
  run:
    - vc  # [win]

test:
  commands:
    - test -e $PREFIX/lib/libusgscsm.so  # [linux]
    - test -e $PREFIX/lib/libusgscsm.dylib  # [osx]
    - if not exist %LIBRARY_BIN%\usgscsm.dll exit 1  # [win]

about:
  home: https://github.com/DOI-USGS/usgscsm
  license: None
summary: "USGS Astrogeology Community Sensor Model compliant sensor models."
