# Generate a C source embedding proj.db as a byte array (see ProjDbData.h).
# Invoked at build time with -DPROJ_DB=<proj.db> -DOUT_C=<output .cpp>.

file(READ "${PROJ_DB}" _hex HEX)

# Break into 16-byte (32 hex character) lines first. One 40+ MB line would
# exceed MSVC's source line limit, and newlines survive the hexify pass below
# while "0x" prefixes would confuse it if the passes were reversed.
string(REGEX REPLACE "(................................)" "\\1\n" _hex "${_hex}")

# Turn the hex pairs into "0x..,0x..," byte initializers.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")

file(SIZE "${PROJ_DB}" _size)

set(_content "// Auto-generated by embed_proj_db.cmake. Do not edit.\n")
string(APPEND _content "#include \"usgscsm/ProjDbData.h\"\n\n")
string(APPEND _content "extern \"C\" const unsigned char usgscsm_proj_db_data[] = {\n")
string(APPEND _content "${_bytes}\n};\n\n")
string(APPEND _content "extern \"C\" const unsigned long long usgscsm_proj_db_size = ${_size}ULL;\n")

file(WRITE "${OUT_C}" "${_content}")
